@startuml
actor Admin
participant MainActivity
participant ApiService
participant ProductController

Admin -> MainActivity: Open Application
MainActivity -> ApiService: getAllProducts()
ApiService -> ProductController:  @GET("/api/products")
ProductController -> ApiService: ProductList
ApiService -> MainActivity: ProductList
MainActivity -> Admin: Show Product List
Admin -> MainActivity: Delete one product
MainActivity -> ApiService: deleteProduct(productId)
ApiService -> ProductController: @DELETE("api/admin/delete_product/{id}")
ProductController --> ApiService: Confirm deletion
ApiService --> MainActivity: Return success message
MainActivity --> Admin: Show feedback
@enduml
